/**
 * Finds the photographs and writes the manifest the site reads.
 *
 * The site never references an image path directly. It asks for a slot —
 * "the-corso/hero", "home/coda" — and gets back a file if one has been
 * supplied and nothing if one has not, in which case the composed plate is
 * drawn instead. That indirection is the whole point: photography can be
 * dropped into public/images and picked up on the next build, with no content
 * edit, no broken <img>, and no half-populated page in between.
 *
 * Run by `prebuild`, so a Vercel deploy always ships a manifest that matches
 * what is actually in the repository.
 *
 *   node tools/media/scan.mjs
 */
import { readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve, extname, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const imagesDir = join(root, "public", "images");
const target = join(root, "src", "content", "media-manifest.ts");

const USABLE = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);

/** Every image under public/images, keyed by its path without an extension. */
function walk(dir, prefix = "") {
  const found = [];
  if (!existsSync(dir)) return found;
  for (const entry of readdirSync(dir).sort()) {
    if (entry.startsWith(".")) continue;
    const full = join(dir, entry);
    const slot = prefix ? `${prefix}/${entry}` : entry;
    if (statSync(full).isDirectory()) {
      found.push(...walk(full, slot));
      continue;
    }
    const ext = extname(entry).toLowerCase();
    if (!USABLE.has(ext)) continue;
    found.push({
      slot: slot.slice(0, slot.length - ext.length),
      path: `/images/${slot}`,
    });
  }
  return found;
}

// "projects/the-corso/hero" is addressed as "the-corso/hero"; everything else
// keeps its folder, so home/ and studio/ slots read the way they are written.
const entries = walk(imagesDir).map(({ slot, path }) => ({
  slot: slot.startsWith("projects/") ? slot.slice("projects/".length) : slot,
  path,
}));

entries.sort((a, b) => a.slot.localeCompare(b.slot));

const body = entries
  .map(({ slot, path }) => `  ${JSON.stringify(slot)}: ${JSON.stringify(path)},`)
  .join("\n");

writeFileSync(
  target,
  `/**
 * Generated by tools/media/scan.mjs — do not edit.
 *
 * Slot to file, for every photograph supplied under public/images. A slot with
 * no entry here is drawn as a composed plate instead, so the site is complete
 * whether the archive is or not.
 */
export const mediaManifest: Record<string, string> = {
${body}
};
`,
);

console.log(
  entries.length
    ? `${entries.length} photograph${entries.length === 1 ? "" : "s"} -> src/content/media-manifest.ts`
    : "no photographs supplied yet — every plate will be drawn",
);
