/**
 * Generated by tools/media/scan.mjs — do not edit.
 *
 * Slot to file, for every photograph supplied under public/images. A slot with
 * no entry here is drawn as a composed plate instead, so the site is complete
 * whether the archive is or not.
 */
export const mediaManifest: Record<string, string> = {

};
